# Generated by Django 5.2 on 2025-05-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'team1', 'team2', 'match_datetime')},
        ),
    ]
