# Generated by Django 5.2 on 2025-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_match_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'team1', 'team2')},
        ),
    ]
