# Generated by Django 5.2 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_event_options_event_results_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='final_standings',
            field=models.JSONField(blank=True, default=dict, help_text='Ви можете скопіювати дані з автоматичної таблиці сюди і відредагувати вручну. Зберігайте валідну JSON структуру.', verbose_name='Фінальна таблиця (офіційна)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='standings',
            field=models.JSONField(blank=True, default=dict, help_text='Розраховується автоматично. Не редагуйте вручну.', verbose_name='Турнірна таблиця (авто)'),
        ),
    ]
